name: Scribe GitHub App Workflow Demo
on: 
    push:
    workflow_dispatch:

env:
  SCRIBE_URL: "https://api.dev.hub.scribesecurity.com/scribe-proxy"
  SCRIBE_LOGIN_URL: "https://scribesec-dev.us.auth0.com"
  SCRIBE_AUDIENCE: "api.dev.scribesecurity.com"

jobs:
  
  scribe-report-test:
    runs-on: ubuntu-latest
    steps:
      - name: create file and Docker
        run: | 
          echo `date` > tmp.txt
          echo "FROM scratch" > Dockerfile
          echo "COPY . ." >> Dockerfile
          docker build -t date:latest .
 
      - uses: actions/checkout@v3
      
      - name: install opa
        run: | 
          curl -L -o opa https://openpolicyagent.org/downloads/v0.46.1/opa_linux_amd64_static
          chmod +x ./opa
          echo "installed"
          whereis opa
          ./opa version
      
      
      - name: Clone GuillaumeFalourd/formulas-training PRIVATE repository
        uses: GuillaumeFalourd/clone-github-repo-action@v2
        with:
            owner: 'scribe-security'
            repository: 'GitHub-Posture'
            access-token: ${{ secrets.GH_ACCESS_TOKEN }}
            
      - name: generate slsa report
        run: | # echo "SLSA is great" > slsa.json
          cat input.json | sed "s/GH_TOKEN/${{ secrets.GH_ACCESS_TOKEN }}/" | ./opa eval -I --format=pretty -b GitHub-Posture/github data.github.branches.successes
